### ISSUE TITLE
更新程序执行一半就关了

### ISSUE THREAD

**Issue by mlmdflr** [mashirooooo/electron_updater#1]
![image](https://user-images.githubusercontent.com/93173537/183611496-eb20c684-dfe8-4513-847d-b47867ea4253.png)

**Comment by mlmdflr** [comment]
补充版本:0.1.1

**Comment by mashirooooo** [comment]
用cli版测试是否一样？

**Comment by mlmdflr** [comment]
cli版本好像没这个问题

**Comment by mashirooooo** [comment]
那应该就是druid在win7上支持不好，直接挂了吧。

**Comment by mashirooooo** [comment]
过段时间我换个ui试试
